#!/bin/bash

# Este script faz parte do projeto final de diac - Drone U818A
#
# Função: atualizar a pasta do projeto, sem interferencia do usuário
# 
# Autor: Lucas Vieira

f="$(git pull)"
echo $f
if [ "$?"="0" ]; then
echo "A atualização foi finalizada corretamente."
else
echo "Erro ao atualizar a pasta do projeto"
fi